version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: parquimetro
    ports:
      - "7072:5432"
    networks:
      - parking-app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7070:80"
    depends_on:
      - postgres
    networks:
      - parking-app-network

  parking-app:
    build:
      context: .
    container_name: parking-app
    ports:
      - "7080:8080"
    depends_on:
      - postgres
      - rabbitMQ
    restart: unless-stopped
    environment:
      DATABASE_HOST: postgres
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${PARKING_EMAIL}
      SPRING_MAIL_PASSWORD: ${EMAIL_API_KEY}
      RABBIT_HOST: rabbitmq
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    networks:
      - parking-app-network

  rabbitMQ:
    image: rabbitmq:3.13-management
    container_name: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "7071:15672"
    networks:
      - parking-app-network

volumes:
  postgres-data:

networks:
  parking-app-network: