version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "parquimetro_db"
    ports:
      - "15432:5432"
    networks:
      - parking-app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - parking-app-network

  parking-app:
    build:
      context: .
    container_name: parking-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/parquimetro_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_MAIL_USERNAME: "parkingfiap860@gmail.com"
      SPRING_MAIL_PASSWORD: "wxhn hnza adsb shqm"
    networks:
      - parking-app-network

  redis:
    container_name: "redis"
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  postgres-data:

networks:
  parking-app-network: